apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: formrecognizer-folder-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: formrecognizer-db-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
---