apiVersion: v1
kind: Service
metadata:
  name: studio
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
  - port: 5000
    targetPort: 5000
  - port: 5001
    targetPort: 5001
  selector:
    app: studio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studio
  template:
    metadata:
      labels:
        app: studio
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: studio
        # image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/studio:3.0
        image: crgarformrecognizeracr.azurecr.io/frstudio/on-prem:dev
        env:
          - name: "AZURECOGNITIVESERVICELAYOUTHOST"
            value: "https://formrecognizer-ns.formrecognizer.svc.cluster.local:5001"
          - name: "ONPREM_LOCALFILE_BASEPATH"
            value: "/onprem_folder"
          - name: "STORAGE_DATABASE_CONNECTION_STRING"
            value: "/onprem_db/Application.db"
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: folder-volume
          mountPath: "/onprem_folder"
        - name: db-volume
          mountPath: "/onprem_db"
      - name: layout
        image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/layout
        env:
          - name: "EULA"
            value: "accept"
          - name: "billing"
            value: "https://crgar-formrecognizer-fr.cognitiveservices.azure.com/"
          - name: "key"
            value: "<Key>"
          - name : "Logging:Console:LogLevel:Default"
            value: "Information"
          - name : "SharedRootFolder" 
            value: "/shared"
          - name : "Mounts:Shared" 
            value: "/shared"
          - name : "Mounts:Output"
            value: "/logs"
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: shared
          mountPath: "/shared"
        - name: output
          mountPath: "/output"
      - name: layout
        image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/custom-template-3.0:latest
        env:
          - name: "AzureCognitiveServiceLayoutHost"
            value: "http://azure-cognitive-service-layout:5000"
          - name: "EULA"
            value: "accept"
          - name: "billing"
            value: "https://crgar-formrecognizer-fr.cognitiveservices.azure.com/"
          - name: "key"
            value: "<key>"
          - name : "Logging:Console:LogLevel:Default"
            value: "Information"
          - name : "SharedRootFolder" 
            value: "/shared"
          - name : "Mounts:Shared" 
            value: "/shared"
          - name : "Mounts:Output"
            value: "/logs"
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: shared
          mountPath: "/shared"
        - name: output
          mountPath: "/output"
      volumes:
      - name: folder-volume
        persistentVolumeClaim:
          claimName: studio-folder-claim
      - name: db-volume
        persistentVolumeClaim:
          claimName: studio-db-claim
            - name: layout
      - name: shared
        persistentVolumeClaim:
          claimName: shared
            - name: layout
      - name: output
        persistentVolumeClaim:
          claimName: output
            - name: layout
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: studio-folder-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: studio-db-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: shared
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: output
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi